package com.example.digital.cookordie;

import java.util.ArrayList;
import java.util.List;

public class DAORecetas {

    public List<Receta> obtenerRecetas(){
        List<Receta> recetas = new ArrayList<>();
        recetas.add(new Receta("Pollo Picante", R.drawable.pollopicante, "1 kilo de pollo, pueden ser muslos o alitas.\n" + "\n" + "1 ajo\n" +"\n" +"1 pedacito de jengibre\n" +"\n" + "2 cebollas de verdeo\n" +  "\n" + "Aceite de ajonjolí\n" + "\n" + "Miel", "Hacer la salsa para marinar con 6 dientes de ajo picados, el trozo de jengibre picado, dos cebollas de verdeo picadas. Añadir a 1 taza de gochugaru, 1 taza de gochujang, media taza de aceite de ajonjolí y media taza de miel.\n" + "\n" + "Añadir la salsa al pollo y dejar marinar alrededor de una hora, si se puede hasta tres. Asar a la parrilla o en horno. ¡Listo! un delicioso pollo picante y dulce estilo coreano."));
        recetas.add(new Receta("Guacamole", R.drawable.guacamole,"3 aguacates maduros\n" + "El jugo de 1 limón\n" + "½ taza de cebolla picadita\n" + "2-3 chiles serranos o ajíes picantes, finamente picados, sin las membranas y sin semillas\n" + "1-2 dientes de ajo, machacados - opcional\n" +"2 cucharadas de cilantro finamente picado\n" + "Sal al gusto\n" + "Opcional – 1-2 tomates, picados en cubitos","Corte los aguacates por la mitad y retire las semillas. Use una cuchara para extraer la pulpa del aguacate, colóquelo en un tazón grande, agregue el jugo de limón, y aplaste los obtener un puré. Puede dejar trocitos pequeños para darle un poco de consistencia. Agregue la cebolla picada, los chiles o ajíes picados, el ajo machacado, el cilantro picado, tomatos (si los va usar) y sal al gusto. Mezcle bien y sirva con chips de tortilla o para acompañar a los platillos mexicanos."));
        recetas.add(new Receta("Pan de Yuca", R.drawable.pandeyuca,"3 aguacates maduros\n" + "El jugo de 1 limón\n" + "½ taza de cebolla picadita\n" + "2-3 chiles serranos o ajíes picantes, finamente picados, sin las membranas y sin semillas\n" + "1-2 dientes de ajo, machacados - opcional\n" +"2 cucharadas de cilantro finamente picado\n" + "Sal al gusto\n" + "Opcional – 1-2 tomates, picados en cubitos","Corte los aguacates por la mitad y retire las semillas. Use una cuchara para extraer la pulpa del aguacate, colóquelo en un tazón grande, agregue el jugo de limón, y aplaste los obtener un puré. Puede dejar trocitos pequeños para darle un poco de consistencia. Agregue la cebolla picada, los chiles o ajíes picados, el ajo machacado, el cilantro picado, tomatos (si los va usar) y sal al gusto. Mezcle bien y sirva con chips de tortilla o para acompañar a los platillos mexicanos."));
        recetas.add(new Receta("Humita", R.drawable.humita,"3 aguacates maduros\n" + "El jugo de 1 limón\n" + "½ taza de cebolla picadita\n" + "2-3 chiles serranos o ajíes picantes, finamente picados, sin las membranas y sin semillas\n" + "1-2 dientes de ajo, machacados - opcional\n" +"2 cucharadas de cilantro finamente picado\n" + "Sal al gusto\n" + "Opcional – 1-2 tomates, picados en cubitos","Corte los aguacates por la mitad y retire las semillas. Use una cuchara para extraer la pulpa del aguacate, colóquelo en un tazón grande, agregue el jugo de limón, y aplaste los obtener un puré. Puede dejar trocitos pequeños para darle un poco de consistencia. Agregue la cebolla picada, los chiles o ajíes picados, el ajo machacado, el cilantro picado, tomatos (si los va usar) y sal al gusto. Mezcle bien y sirva con chips de tortilla o para acompañar a los platillos mexicanos."));
        recetas.add(new Receta("Empanada de Tasajo", R.drawable.empanadas,"3 aguacates maduros\n" + "El jugo de 1 limón\n" + "½ taza de cebolla picadita\n" + "2-3 chiles serranos o ajíes picantes, finamente picados, sin las membranas y sin semillas\n" + "1-2 dientes de ajo, machacados - opcional\n" +"2 cucharadas de cilantro finamente picado\n" + "Sal al gusto\n" + "Opcional – 1-2 tomates, picados en cubitos","Corte los aguacates por la mitad y retire las semillas. Use una cuchara para extraer la pulpa del aguacate, colóquelo en un tazón grande, agregue el jugo de limón, y aplaste los obtener un puré. Puede dejar trocitos pequeños para darle un poco de consistencia. Agregue la cebolla picada, los chiles o ajíes picados, el ajo machacado, el cilantro picado, tomatos (si los va usar) y sal al gusto. Mezcle bien y sirva con chips de tortilla o para acompañar a los platillos mexicanos."));
        recetas.add(new Receta("Alfajor de Fernet", R.drawable.alfajor,"3 aguacates maduros\n" + "El jugo de 1 limón\n" + "½ taza de cebolla picadita\n" + "2-3 chiles serranos o ajíes picantes, finamente picados, sin las membranas y sin semillas\n" + "1-2 dientes de ajo, machacados - opcional\n" +"2 cucharadas de cilantro finamente picado\n" + "Sal al gusto\n" + "Opcional – 1-2 tomates, picados en cubitos","Corte los aguacates por la mitad y retire las semillas. Use una cuchara para extraer la pulpa del aguacate, colóquelo en un tazón grande, agregue el jugo de limón, y aplaste los obtener un puré. Puede dejar trocitos pequeños para darle un poco de consistencia. Agregue la cebolla picada, los chiles o ajíes picados, el ajo machacado, el cilantro picado, tomatos (si los va usar) y sal al gusto. Mezcle bien y sirva con chips de tortilla o para acompañar a los platillos mexicanos."));
        recetas.add(new Receta("Asado", R.drawable.asado,"3 aguacates maduros\n" + "El jugo de 1 limón\n" + "½ taza de cebolla picadita\n" + "2-3 chiles serranos o ajíes picantes, finamente picados, sin las membranas y sin semillas\n" + "1-2 dientes de ajo, machacados - opcional\n" +"2 cucharadas de cilantro finamente picado\n" + "Sal al gusto\n" + "Opcional – 1-2 tomates, picados en cubitos","Corte los aguacates por la mitad y retire las semillas. Use una cuchara para extraer la pulpa del aguacate, colóquelo en un tazón grande, agregue el jugo de limón, y aplaste los obtener un puré. Puede dejar trocitos pequeños para darle un poco de consistencia. Agregue la cebolla picada, los chiles o ajíes picados, el ajo machacado, el cilantro picado, tomatos (si los va usar) y sal al gusto. Mezcle bien y sirva con chips de tortilla o para acompañar a los platillos mexicanos."));
        recetas.add(new Receta("Mondongo", R.drawable.mondongo,"3 aguacates maduros\n" + "El jugo de 1 limón\n" + "½ taza de cebolla picadita\n" + "2-3 chiles serranos o ajíes picantes, finamente picados, sin las membranas y sin semillas\n" + "1-2 dientes de ajo, machacados - opcional\n" +"2 cucharadas de cilantro finamente picado\n" + "Sal al gusto\n" + "Opcional – 1-2 tomates, picados en cubitos","Corte los aguacates por la mitad y retire las semillas. Use una cuchara para extraer la pulpa del aguacate, colóquelo en un tazón grande, agregue el jugo de limón, y aplaste los obtener un puré. Puede dejar trocitos pequeños para darle un poco de consistencia. Agregue la cebolla picada, los chiles o ajíes picados, el ajo machacado, el cilantro picado, tomatos (si los va usar) y sal al gusto. Mezcle bien y sirva con chips de tortilla o para acompañar a los platillos mexicanos."));


        return recetas;
    }
}
